import type { Car, Booking } from './types';

export const cars: Car[] = [
  {
    id: '1',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    type: 'Sedan',
    pricePerDay: 75,
    location: 'Los Angeles, CA',
    availability: true,
    features: ['Autopilot', 'Premium Interior', 'Heated Seats', 'GPS Navigation', 'Sunroof'],
    images: [
      'https://picsum.photos/seed/car1a/1024/768',
      'https://picsum.photos/seed/car1b/1024/768',
      'https://picsum.photos/seed/car1c/1024/768',
    ],
    description: 'Experience the future of driving with the Tesla Model 3. Sleek, safe, and efficient, it offers exhilarating performance and a state-of-the-art interior.',
  },
  {
    id: '2',
    make: 'Ford',
    model: 'Mustang Mach-E',
    year: 2022,
    type: 'SUV',
    pricePerDay: 85,
    location: 'Miami, FL',
    availability: true,
    features: ['Electric', 'Large Touchscreen', 'Advanced Safety Features', 'Panoramic Roof'],
    images: [
      'https://picsum.photos/seed/car2a/1024/768',
      'https://picsum.photos/seed/car2b/1024/768',
      'https://picsum.photos/seed/car2c/1024/768',
    ],
    description: 'The Ford Mustang Mach-E combines iconic Mustang heritage with all-electric power. Enjoy thrilling acceleration and a spacious, modern cabin.',
  },
  {
    id: '3',
    make: 'Porsche',
    model: '911 Carrera',
    year: 2023,
    type: 'Sports',
    pricePerDay: 350,
    location: 'Beverly Hills, CA',
    availability: false,
    features: ['Sport Chrono Package', 'Leather Interior', 'Bose Surround Sound', 'Dynamic Chassis Control'],
    images: [
      'https://picsum.photos/seed/car3a/1024/768',
      'https://picsum.photos/seed/car3b/1024/768',
      'https://picsum.photos/seed/car3c/1024/768',
    ],
    description: 'The legendary Porsche 911 Carrera delivers an unparalleled driving experience. With its powerful engine and precision handling, every drive is an event.',
  },
  {
    id: '4',
    make: 'Audi',
    model: 'A3',
    year: 2022,
    type: 'Hatchback',
    pricePerDay: 60,
    location: 'Chicago, IL',
    availability: true,
    features: ['Virtual Cockpit', 'Apple CarPlay', 'Parking Sensors', 'Keyless Entry'],
    images: [
      'https://picsum.photos/seed/car4a/1024/768',
      'https://picsum.photos/seed/car4b/1024/768',
      'https://picsum.photos/seed/car4c/1024/768',
    ],
    description: 'The Audi A3 is a premium hatchback that offers a perfect blend of style, technology, and practicality. Ideal for city driving and weekend getaways.',
  },
  {
    id: '5',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2023,
    type: 'Luxury',
    pricePerDay: 450,
    location: 'New York, NY',
    availability: true,
    features: ['Executive Rear Seat Package', 'Burmester 3D Surround Sound', 'Air Balance Fragrance System', 'Massage Seats'],
    images: [
      'https://picsum.photos/seed/car5a/1024/768',
      'https://picsum.photos/seed/car5b/1024/768',
      'https://picsum.photos/seed/car5c/1024/768',
    ],
    description: 'Indulge in the pinnacle of automotive luxury with the Mercedes-Benz S-Class. It sets the standard for comfort, innovation, and refinement.',
  },
  {
    id: '6',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2021,
    type: 'SUV',
    pricePerDay: 90,
    location: 'Denver, CO',
    availability: true,
    features: ['4x4', 'Removable Top', 'All-Terrain Tires', 'Uconnect Infotainment'],
    images: [
      'https://picsum.photos/seed/car6a/1024/768',
      'https://picsum.photos/seed/car6b/1024/768',
      'https://picsum.photos/seed/car6c/1024/768',
    ],
    description: 'The iconic Jeep Wrangler is built for adventure. Conquer any terrain with its legendary off-road capability and rugged design.',
  },
];

export const bookings: Booking[] = [
  {
    id: 'b1',
    carId: '2',
    userId: 'u1',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2024-08-05'),
    totalPrice: 340,
    status: 'accepted',
  },
  {
    id: 'b2',
    carId: '5',
    userId: 'u1',
    startDate: new Date('2024-09-10'),
    endDate: new Date('2024-09-12'),
    totalPrice: 900,
    status: 'pending',
  },
  {
    id: 'b3',
    carId: '1',
    userId: 'u2',
    startDate: new Date('2024-07-20'),
    endDate: new Date('2024-07-22'),
    totalPrice: 150,
    status: 'cancelled',
  },
    {
    id: 'b4',
    carId: '3',
    userId: 'u3',
    startDate: new Date('2024-08-15'),
    endDate: new Date('2024-08-20'),
    totalPrice: 1750,
    status: 'accepted',
  },
  {
    id: 'b5',
    carId: '4',
    userId: 'u2',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-06-05'),
    totalPrice: 240,
    status: 'completed',
  },
  {
    id: 'b6',
    carId: '6',
    userId: 'u3',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2024-09-03'),
    totalPrice: 180,
    status: 'rejected',
  }
];
